scalar Date
scalar DateTime

type Query {
    aboutMe: AboutMe
}

type Mutation {
    doLogin(input: LoginInput!): String
}

type AboutMe {
    user: User
}

input LoginInput {
    firebaseUUID: String!
    email: String!
}