scalar Date
scalar DateTime

type Query{
    allJobs(start: Int, max: Int): [Job]
    getJobById(id: ID!): Job
    allJobsPaginated(page: Int!, limit: Int!): PaginatedListJob
    debugJob: [Job],
    allJobsFeatured(start: Int, max: Int, featured: Boolean!): [Job]
    listJobRandomFeatured: [Job]
    getJobByCompanyId(companyId: ID!) : [Job]
    getJobByIdAndCompanyId(id: ID!, companyId: ID!) : Job
    myJobs: [Job]
}

type Mutation {
    createJob(input: JobInput!): Job
    deleteJob(id: ID!) : Boolean
    updateJob(id: ID!, input: JobInput!): Job
    subscribeInJob(input: SubscribeInJobInput!): Boolean
}


type Job {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    active: Boolean
    benefits: String
    description: String
    feature: Boolean
    jobCategory: JobCategory
    jobType: JobType
    maxPayment: Float
    minPayment: Float
    requirement: String
    title: String
    company: Company
    candidates: [Candidate]
}

input JobInput {
    active: Boolean!
    benefits: String!
    description: String!
    feature: Boolean!
    jobCategory: JobCategory!
    jobType: JobType!
    maxPayment: Float!
    minPayment: Float!
    requirement: String!
    title: String!
    company_id: Int!
}

enum JobCategory {
    MANAGEMENT, OPERATOR
}

enum JobType {
    FREELANCE, FULLTIME, INTERNSHIP, PARTTIME, TEMPORARY, VOLUNTEER
}


type PaginatedListJob {
    rows: [Job]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

input SubscribeInJobInput{
    jobId: ID!
    candidateId: ID!
}