scalar Date
scalar DateTime

type Query {
    allTestimonials(start: Int, max: Int): [Testimonial]
    getTestimonialById(id: ID!): Testimonial
    allTestimonialsPaginated(page: Int!, limit: Int!): PaginatedListTestimonial
}

type Mutation {
    createTestimonial(input: TestimonialInput!): Testimonial
    deleteTestimonial(id: ID!) : Boolean
    updateTestimonial(id: ID!, input: TestimonialInput!): Testimonial
}

type Testimonial{
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    picture: String
    signature: String
    text: String
    author: Author
}

input TestimonialInput {
    picture: String!
    signature: String!
    text: String!
    author_id: Int!
}

type PaginatedListTestimonial {
    rows: [Testimonial]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}