scalar Date
scalar DateTime

type Query {
    allCompanies(start: Int, max: Int): [Company]
    getCompanyById(id: ID!): Company
    allCompaniesPaginated(page: Int!, limit: Int!): PaginatedListCompany
    listCompanyRandomLogos(start: Int, max: Int): [Logo]
}

type Mutation {
    createCompany(input: CompanyInput!): Company
    deleteCompany(id: ID!) : Boolean
    updateCompany(id: ID!, input: CompanyInput!): Company    
}

type Company {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    mobilePhone: Int
    city: String
    estate: String
    neighborhood: String
    number: String
    street: String
    zipCode: Int
    name: String
    cnpj: Float
    description: String
    logo: String
    segment: String
    user: User
    medias: [CompanyMedia]
}

input CompanyInput {    
    mobilePhone: Int!
    city: String!
    estate: String!
    neighborhood: String!
    number: String!
    street: String!
    zipCode: Int!
    name: String!
    cnpj: Float!
    description: String!
    logo: String!
    segment: String!
    user_id: Int!
    medias: [CompanyMediaInput]  
}

input CompanyMediaInput {
  media: String!
  url: String!
}

  type CompanyMedia {    
    media: String,
    url: String
  }  

  type PaginatedListCompany {
    rows: [Company]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

type Logo {
  id: ID
  name: String
  logo: String
}