scalar Date
scalar DateTime

type Query {
    companyPage(id: ID!): CompanyPage
    companyFollowersCount(companyId: ID!): Int
}

type Mutation {
    createCompanyPage(creatorUserId: ID!, input: CompanyPageInput!): CompanyPage
    followCompany(companyId: ID!, userId: ID!): Boolean
    unfollowCompany(companyId: ID!, userId: ID!): Boolean
}

type CompanyPage {
    id: ID
    name: String
    industry: String
    size: String
    logoUrl: String
    bannerUrl: String
    description: String
    createdAt: DateTime
    updatedAt: DateTime
}

input CompanyPageInput {
    name: String!
    industry: String
    size: String
    logoUrl: String
    bannerUrl: String
    description: String
}