scalar Date
scalar DateTime

type Query {
    allMembers(start: Int, max: Int): [Member]
    getMemberById(id: ID!): Member
    allMembersPaginated(page: Int!, limit: Int!): PaginatedListMember
}

type Mutation {
    createMember(input: MemberInput!): Member
    deleteMember(id: ID!) : Boolean
    updateMember(id: ID!, input: MemberInput!): Member
}

type Member {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    name: String
    occupation: String
    picture: String
    shortText: String
    medias: [MemberMedia]
}

input MemberInput {
    name: String!
    occupation: String!
    picture: String!
    shortText: String!
    medias: [MemberMediaInput]
}

type MemberMedia{
    owner: Member
    media: String
    url: String
}

input MemberMediaInput {
    media: String!
    url: String!
}

type PaginatedListMember {
    members: [Member]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}