scalar Date
scalar DateTime

type Query {
    event(id: ID!): Event
    eventAttendees(eventId: ID!, limit: Int, offset: Int): [EventAttendee]
}

type Mutation {
    createEvent(organizerId: ID!, title: String!, description: String, eventType: String, startTime: DateTime!, endTime: DateTime, locationOrUrl: String): Event
    attendEvent(eventId: ID!, userId: ID!, status: String): EventAttendee
}

type Event {
    id: ID
    title: String
    description: String
    eventType: String
    startTime: DateTime
    endTime: DateTime
    locationOrUrl: String
    organizerId: ID
    organizer: User
    createdAt: DateTime
    updatedAt: DateTime
}

type EventAttendee {
    id: ID
    eventId: ID
    event: Event
    userId: ID
    user: User
    status: String
    createdAt: DateTime
}

