scalar Date
scalar DateTime

type Query{
    allJAASUsers(start: Int, max: Int): [JAASUser]
    getJAASUserById(id: ID!): JAASUser
    allJAASUsersPaginated(page: Int!, limit: Int!): PaginatedListJAASUser
    allJAASRoles(start: Int, max: Int): [JAASRole]
    getJAASRoleByName(name: String!): JAASRole
    allJAASRolesPaginated(page: Int!, limit: Int!): PaginatedListJAASRole
}

type Mutation {
    createJAASUser(input: JAASUserInput!): JAASUser
    deleteJAASUser(id: ID!) : Boolean
    updateJAASUser(id: ID!, input: JAASUserInput!): JAASUser
    createJAASRole(input: JAASRoleInput!): JAASRole
    deleteJAASRole(name: String!) : Boolean
    updateJAASRole(name: String!, input: JAASRoleInput!): JAASRole
}

type JAASUser {
    id: ID
    login: String
    password: String
    roles: [JAASRole]
}

input JAASUserInput {
    login: String!
    password: String!
    roles: [JAASRoleInput]
}

input JAASRoleInput {
    name: String!
}

type JAASRole {
    name: String
}

type PaginatedListJAASUser {
    jaasUsers: [JAASUser]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

type PaginatedListJAASRole {
    jaasRoles: [JAASRole]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}