scalar Date
scalar DateTime

type Query{
    allJAASUsers: [JAASUser]
    allJAASRoles: [JAASRole]
}

type JAASUser {
    id: ID
    login: String
    password: String
    roles: [JAASRole]
}

type JAASRole {
    name: String
}