INSERT INTO companies_medias (id, media, url) VALUES (1, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (1, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (1, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (2, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (2, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (2, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (3, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (3, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (3, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (4, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (4, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (4, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (5, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (5, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (5, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (6, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (6, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (6, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (7, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (7, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (7, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (8, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (8, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (8, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (9, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (9, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (9, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (10, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (10, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (10, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (11, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (11, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (11, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (12, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (12, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (12, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (13, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (13, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (13, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (14, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (14, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (14, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (15, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (15, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (15, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (16, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (16, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (16, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (17, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (17, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (17, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (18, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (18, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (18, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (19, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (19, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (19, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (20, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (20, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (20, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (21, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (21, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (21, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (22, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (22, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (22, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (23, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (23, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (23, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (24, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (24, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (24, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (25, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (25, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (25, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (26, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (26, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (26, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (27, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (27, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (27, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (28, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (28, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (28, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (29, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (29, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (29, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (30, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (30, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (30, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (31, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (31, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (31, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (32, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (32, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (32, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (33, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (33, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (33, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (34, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (34, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (34, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (35, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (35, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (35, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (36, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (36, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (36, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (37, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (37, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (37, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (38, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (38, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (38, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (39, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (39, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (39, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (40, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (40, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (40, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (41, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (41, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (41, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (42, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (42, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (42, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (43, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (43, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (43, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (44, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (44, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (44, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (45, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (45, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (45, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (46, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (46, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (46, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (47, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (47, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (47, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (48, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (48, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (48, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (49, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (49, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (49, 'Google Plus', 'http://www.plus.google.com');
INSERT INTO companies_medias (id, media, url) VALUES (50, 'Facebook', 'http://www.facebook.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (50, 'Twitter', 'http://www.twitter.com.br');
INSERT INTO companies_medias (id, media, url) VALUES (50, 'Google Plus', 'http://www.plus.google.com');