INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '01baf5d7-02d7-4769-b0df-1d7bff6dd8b7', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 1 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 1', 'OFFICE', 1);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '98944a96-b48f-4093-b8d9-09148427c823', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 2 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 2', 'OFFICE', 2);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'd1efa262-9145-4ab5-922a-df3523af3c50', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 3 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 3', 'OFFICE', 3);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'd472d0a9-384f-4462-852f-bbbd0f6b24f6', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 4 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 4', 'OFFICE', 4);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'bc882ba1-1e56-4df2-97d1-cb84b9434e11', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 5 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 5', 'OFFICE', 5);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'b2edf2df-ed0e-4837-987b-f65ba0ae07ea', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 6 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 6', 'OFFICE', 6);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '2a4f7646-a883-4bdd-96e0-7d6ad9409835', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 7 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 7', 'OFFICE', 7);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '6e7d0c09-6eb2-4d73-a205-3a6f27f5424b', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 8 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 8', 'OFFICE', 8);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '289ca264-67ad-4890-8eae-4d2c305b3a1a', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 9 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 9', 'OFFICE', 9);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'f9fcd904-b8d3-44e8-9eff-52b8c67037c3', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 10 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 10', 'OFFICE', 10);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '6fab1f15-b41f-479f-b1a8-7ced8fe35ba6', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 11 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 11', 'OFFICE', 11);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '4362be5e-db28-45b0-96c3-19ecf708104d', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 12 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 12', 'OFFICE', 12);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '8afc610b-e17b-4c73-b497-a115b480e348', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 13 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 13', 'OFFICE', 13);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'e04dd793-040f-47b4-abde-41e0e86c91c0', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 14 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 14', 'OFFICE', 14);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '3eba9f22-27a6-4e82-8fc5-2ab63cc3c931', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 15 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 15', 'OFFICE', 15);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'e9b8c56a-b57a-4efc-a6c6-9d92da0c2e25', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 16 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 16', 'OFFICE', 16);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '287e78b6-f7e4-47ef-b16e-9df59b0670f5', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 17 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 17', 'OFFICE', 17);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '0dab93b8-7fc4-4910-9fc9-686316efdf6b', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 18 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 18', 'OFFICE', 18);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '461a0e45-ecc4-4d85-bced-c4e805b529a8', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 19 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 19', 'OFFICE', 19);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '2bc949fb-7a5d-40d3-a1e4-b2bbe96f4e25', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 20 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 20', 'OFFICE', 20);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'd90aea7d-e9a1-49e8-a740-93dfab984fb0', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 21 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 21', 'OFFICE', 21);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'fd4b1569-37c0-42d0-a285-270c30ecb01c', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 22 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 22', 'OFFICE', 22);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '443f8485-dae0-4218-8ce7-a4b2660e9013', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 23 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 23', 'OFFICE', 23);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '49add91c-c92c-42d3-8b4f-b80cea2bf48c', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 24 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 24', 'OFFICE', 24);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '47158a8f-9d3a-4bc3-b0e2-990e418a611a', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 25 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 25', 'OFFICE', 25);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', 'eb0240a7-dd13-4703-a93c-bd77b46046a5', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 26 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 26', 'OFFICE', 26);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '5bcf988c-cdc4-4ceb-87c3-8bbb63f420df', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 27 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 27', 'OFFICE', 27);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '7725f322-895d-4f60-b4b9-f552b2be19a2', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 28 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 28', 'OFFICE', 28);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:34', '2022-07-11 09:35:34', '9f36b883-53d8-4d53-aa6e-47f2b808d741', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 29 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 29', 'OFFICE', 29);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'c8aaf883-d192-4627-8778-52a10ab431f6', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 30 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 30', 'OFFICE', 30);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'f5f8fe29-b0b9-4402-a1eb-3159920a9acb', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 31 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 31', 'OFFICE', 31);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'd152ce09-9b8a-40d7-98db-6dbb9d307b8b', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 32 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 32', 'OFFICE', 32);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'f89fca1d-f07c-4d3d-bccf-d84b165637e6', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 33 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 33', 'OFFICE', 33);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'f8b271cd-4649-42da-8aa1-290486683649', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 34 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 34', 'OFFICE', 34);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '52ac6ebc-b1d0-4aba-9dcd-13ae86cf1800', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 35 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 35', 'OFFICE', 35);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '61222249-557b-4b52-ac29-9a6d21e20d76', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 36 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 36', 'OFFICE', 36);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '93f9baf2-e3fd-4b9b-8357-bf77d8572b08', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 37 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 37', 'OFFICE', 37);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '80d1fe58-e3bb-4384-b32d-1f7f4f763d7f', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 38 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 38', 'OFFICE', 38);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '7fd33ad4-21c7-4d80-bb14-c6d993b95578', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 39 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 39', 'OFFICE', 39);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '9d0f1044-6417-43ea-8598-293e2a82165a', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 40 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 40', 'OFFICE', 40);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'ee444cbc-8e11-4144-9161-7cd261fdd732', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 41 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 41', 'OFFICE', 41);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '3ebd1cfa-c627-48f5-90e6-3af8164ccab7', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 42 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 42', 'OFFICE', 42);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '78c30885-88ae-429f-bfcd-273be766a479', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 43 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 43', 'OFFICE', 43);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '78878e8c-b02e-4888-8051-010ab51e3d0c', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 44 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 44', 'OFFICE', 44);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '67479d61-7794-4a2e-baa1-709011fe3203', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 45 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 45', 'OFFICE', 45);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '9f03b009-e182-48df-a728-93addcf61c21', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 46 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 46', 'OFFICE', 46);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', 'bcaeee16-4d60-47cc-8193-1904392258d9', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 47 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 47', 'OFFICE', 47);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '4e7bc095-2e36-4f0d-8dd5-619ea8b59581', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 48 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 48', 'OFFICE', 48);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '2a9f89ba-166c-4bbc-8dc1-325af9a7f88f', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 49 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 49', 'OFFICE', 49);
INSERT INTO resumes (created_at, updated_at, uuid, carrer_level, content, objective, presence, candidate_id) VALUES ('2022-07-11 09:35:35', '2022-07-11 09:35:35', '4f42728c-ca3c-400b-bc7c-d1d65e1edc4e', 'EXPERT', 'Conteúdo de Candidato ''Mockup'' N# 50 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Objetivo do Candidato ''Mockup'' N# 50', 'OFFICE', 50);
