scalar Date
scalar DateTime

type Query {
    allCandidates(start: Int, max: Int): [Candidate]
    allCandidatesRedis: [Candidate]
    getCandidateById(id: ID!): Candidate
    allCandidatesPaginated(page: Int!, limit: Int!): PaginatedListCandidate
}

type Mutation {
    createCandidate(input: CandidateInput!): Candidate
    deleteCandidate(id: ID!) : Boolean
    updateCandidate(id: ID!, input: CandidateInput!): Candidate
    notifyCandidate(input: NotificationInput!): Boolean
}

type Candidate {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    mobilePhone: Float
    city: String
    state: String
    neighborhood: String
    number: String
    street: String
    zipCode: Int
    name: String
    birthDate: Date
    cpf: Float   
    user: User 
    resume: Resume
}

input CandidateInput {    
    mobilePhone: Float!
    city: String!
    state: String!
    neighborhood: String!
    number: String!
    street: String!
    zipCode: Int!
    name: String!
    birthDate: Date!
    cpf: Float!   
    userId: Int!    
}

type PaginatedListCandidate {
    candidates: [Candidate]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

input NotificationInput {
    type: NotificationType!
    userId: Int!
    title: String!
    message: String!
}

enum NotificationType {
    MAIL,
    PUSH
}
