scalar Date
scalar DateTime

type Query {
    allSelectiveProcesses(start: Int, max: Int): [SelectiveProcess]
    getSelectiveProcessById(id: ID!): SelectiveProcess
    allSelectiveProcessesPaginated(page: Int!, limit: Int!): PaginatedListSelectiveProcess
    mySelectiveProcessesSubscribed: [SelectiveProcess]
    mySelectiveProcesses: [SelectiveProcess]
}

type Mutation {
    createSelectiveProcess(input: SelectiveProcessInput!): SelectiveProcess
    deleteSelectiveProcess(id: ID!) : Boolean
    updateSelectiveProcess(id: ID!, input: SelectiveProcessInput!): SelectiveProcess
    subscribeInSelectiveProcess(input: SubscribeInSelectiveProcessInput!): Boolean
}

type SelectiveProcess {
    id: ID,
    activated: Boolean
    createdAt: DateTime
    disabledAt: DateTime
    expiresIn: DateTime
    maxCandidates: Int
    startsIn: DateTime
    updatedAt: DateTime
    uuid: String
    job: Job
    candidates: [Candidate]
}

input SelectiveProcessInput {
    activated: Boolean!
    disabledAt: DateTime
    expiresIn: DateTime
    maxCandidates: Int!
    startsIn: DateTime!
    jobId: Int!
}

type PaginatedListSelectiveProcess {
    selectiveProcesses: [SelectiveProcess]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

input SubscribeInSelectiveProcessInput{
    spId: ID!
    candidateId: ID!
}