scalar Date
scalar DateTime

type Query {
    allSelectiveProcesses(start: Int, max: Int): [SelectiveProcess]
    getSelectiveProcessById(id: ID!): SelectiveProcess
    allSelectiveProcessesPaginated(page: Int!, limit: Int!): PaginatedListSelectiveProcess
}

type Mutation {
    createSelectiveProcess(input: SelectiveProcessInput!): SelectiveProcess
    deleteSelectiveProcess(id: ID!) : Boolean
    updateSelectiveProcess(id: ID!, input: SelectiveProcessInput!): SelectiveProcess
    subscribeInSelectiveProcess(input: SubscribeInSelectiveProcessInput!): Boolean
}

type SelectiveProcess {
    id: ID,
    active: Boolean
    createdAt: DateTime
    disabledAt: DateTime
    expire: DateTime
    maxCandidates: Int
    start: DateTime
    updatedAt: DateTime
    uuid: String
    job: Job
    candidates: [Candidate]
}

input SelectiveProcessInput {
    active: Boolean!
    disabledAt: DateTime
    expire: DateTime
    maxCandidates: Int!
    start: DateTime!
    job_id: Int!
}

type PaginatedListSelectiveProcess {
    rows: [SelectiveProcess]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

input SubscribeInSelectiveProcessInput{
    spId: ID!
    candidateId: ID!
}