scalar Date
scalar DateTime

type Query {
    allUsers: [User]
    getUserById(id: ID): User
}

type User {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    active: Boolean
    email: String
    firebaseMessageToken: String
    firebaseUUID: String
}