scalar Date
scalar DateTime

type Query {
    allUsers(start: Int, max: Int): [User]
    getUserById(id: ID!): User
    allUsersPaginated(page: Int!, limit: Int!): PaginatedListUser
    deepSearchUser(term: String!): [ElasticUser]
}

type Mutation {
    createUser(input: UserInput!): User
    deleteUser(id: ID!) : Boolean
    updateUser(id: ID!, input: UserInput!): User
}

type ElasticUser {
    id: ID
    score: Float
    user: User
}

type User {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    activated: Boolean
    email: String
    firebaseMessageToken: String
    firebaseUUID: String
}

input UserInput {
    activated: Boolean!
    email: String!
    firebaseMessageToken: String
    firebaseUUID: String!
}

type PaginatedListUser {
    rows: [User]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}