scalar Date
scalar DateTime

type Query {
    allUsers(start: Int, max: Int): [User]
    getUserById(id: ID!): User
}

type Mutation {
    createUser(input: UserInput!): User
}

type User {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    active: Boolean
    email: String
    firebaseMessageToken: String
    firebaseUUID: String
}

input UserInput {
    active: Boolean!
    email: String!
    firebaseMessageToken: String
    firebaseUUID: String!
}