scalar Date
scalar DateTime

type Query {
    allBlogs(start: Int, max: Int): [Blog]
    getBlogById(id: ID!): Blog
    allBlogsPaginated(page: Int!, limit: Int!): PaginatedListBlog
    debugBlog: [Blog]  
    allComments(start: Int, max: Int): [Comment]
    getCommentById(id: ID!): Comment
    allCommentsPaginated(page: Int!, limit: Int!): PaginatedListComment
    debugComment: [Comment]
    allBlogsCategories: [String]
    allBlogsTimePeriods: [TimePeriod],
    allBlogsRecents(start: Int, max: Int): [Blog],
    allCommentsRecents(start: Int, max: Int): [Comment]
}

  type Mutation {
    createBlog(input: BlogInput!): Blog
    deleteBlog(id: ID!) : Boolean
    updateBlog(id: ID!, input: BlogInput!): Blog
    createComment(input: CommentInput!): Comment
    deleteComment(id: ID!, blog_id: ID!) : Boolean
    updateComment(id: ID!, input: CommentInput!): Comment
}

type Picture {
    blog: Blog
    pictures: String
}

type Tag {
    blog: Blog
    name: String
}

type Blog {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    category: String
    citation: String
    content: String
    date: Date
    resume: String
    title: String
    author: Author
    comments: [Comment]  
    pictures: [Picture]
    tags: [Tag]
}

  input BlogInput {
    category: String!
    citation: String!
    content: String!
    date: Date!
    resume: String!
    title: String!
    author_id: Int
    comments: [CommentInput]  
    pictures: [PictureInput]
    tags: [TagInput]
}

input CommentInput {
    blog_id: Int
    email: String!
    name: String!
    text: String!    
}

input PictureInput {
    pictures: String!
}

input TagInput{
    name: String!
}

type Comment {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    email: String
    name: String
    text: String
    blog: Blog
}

type PaginatedListBlog {
    rows: [Blog]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

type PaginatedListComment {
    rows: [Comment]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}

type TimePeriod {
    year: Int
    month: Int
}