scalar Date
scalar DateTime

type Query {
    allBlogs: [Blog]
    allComments: [Comment]
}

type Blog {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    category: String
    citation: String
    content: String
    date: Date
    resume: String
    title: String
    author: Author
    comments: [Comment]  
}

type Comment {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    email: String
    name: String
    text: String
}