scalar Date
scalar DateTime

type Query {    
    allAuthors(start: Int, max: Int): [Author]
    getAuthorById(id: ID!): Author
    allAuthorsPaginated(page: Int!, limit: Int!): PaginatedListAuthor
    debugAuthor: [Author]    
  }

  type Mutation {
    createAuthor(input: AuthorInput!): Author
    deleteAuthor(id: ID!) : Boolean
    updateAuthor(id: ID!, input: AuthorInput!): Author
}

  type Author {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String    
    aboutText: String
    name: String
    picture: String
    medias: [AuthorMedia]
  }

  type AuthorMedia {
    author: Author
    media: String
    url: String
  }  

  input AuthorInput {
    aboutText: String!
    name: String!
    picture: String!
    medias: [AuthorMediaInput]
}

input AuthorMediaInput {
  media: String!
  url: String!
}


type PaginatedListAuthor {
    authors: [Author]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}