scalar Date

type Query {
    hello: String
    allAuthors: [Author]    
  }

  type Author {
    id: ID,
    createdAt: String
    updatedAt: String
    uuid: String    
    aboutText: String
    name: String
    picture: String,
    medias: [Media]
  }

  type Media {
    author: Author,
    media: String,
    url: String
  }  