scalar Date
scalar DateTime

type Query {
    allResumes(start: Int, max: Int): [Resume]  
    getResumeById(id: ID!): Resume
    allResumesPaginated(page: Int!, limit: Int!): PaginatedListResume  
}

type Mutation {
    createResume(input: ResumeInput!): Resume
    deleteResume(id: ID!) : Boolean
    updateResume(id: ID!, input: ResumeInput!): Resume
}

type Resume {
    id: ID,
    createdAt: DateTime
    updatedAt: DateTime
    uuid: String
    carrerLevel: CarrerLevel
    content: String
    objective: String
    presence: Presence
    candidate: Candidate
    educations: [Education]
    experiences: [Experience]
    skills: [Skill]
}

input ResumeInput {
    carrerLevel: CarrerLevel!
    content: String!
    objective: String!
    presence: Presence!
    candidate_id: Int!
    educations: [EducationInput]
    experiences: [ExperienceInput]
    skills: [SkillInput]
}

input EducationInput {
    description: String!
    endDate: Date
    qualification: String!
    schoolName: String!
    startDate: Date!
}

input ExperienceInput {
    description: String!
    employerName: String!
    endDate: Date
    jobTitle: String!
    startDate: Date!
    responsibilities: String!
}

input SkillInput {
    skillName: String!
    months: Int!
}

enum CarrerLevel{
    JUNIOR,
    MIDDLE,
    SENIOR,
    EXPERT
}

enum Presence {
    REMOTE,
    OFFICE,
    RELOCATION,
    TRAVEL_A_LOT
}

type Education {
    id: ID
    description: String
    endDate: Date
    qualification: String
    schoolName: String
    startDate: Date
}

type Experience {
    id: ID
    description: String
    employerName: String
    endDate: Date
    jobTitle: String
    startDate: Date
    responsibilities: String
}

type Skill {
    id: ID
    skillName: String
    months: Int
}

type PaginatedListResume {
    rows: [Resume]
    start: Int
    end: Int,
    totalPages: Int,
    currentPage: Int,
    limitRows: Int,
    maxRows: Int
}