scalar Date
scalar DateTime

type Query {
    skillEndorsements(skillId: ID!): [SkillEndorsement]
    userRecommendations(userId: ID!): [Recommendation]
    userSkillsWithEndorsements(userId: ID!, currentUserId: ID): [SkillWithEndorsementInfo]
}

type Mutation {
    endorseSkill(skillId: ID!, endorserId: ID!): Boolean
    unendorseSkill(skillId: ID!, endorserId: ID!): Boolean
    createRecommendation(recommenderId: ID!, recipientId: ID!, content: String!): Recommendation
    respondToRecommendation(recommendationId: ID!, recipientId: ID!, accept: Boolean!): Recommendation
    addUserSkill(userId: ID!, skillName: String!): SkillWithEndorsementInfo
    removeUserSkill(userId: ID!, skillId: ID!): Boolean
}

type SkillWithEndorsementInfo {
    id: ID!
    name: String!
    endorsementsCount: Int!
    isEndorsedByMe: Boolean
}

type SkillEndorsement {
    id: ID
    skillId: ID
    endorserId: ID
    endorser: User
    createdAt: DateTime
}

type Recommendation {
    id: ID
    recommenderId: ID
    recommender: User
    recipientId: ID
    recipient: User
    content: String
    status: String
    createdAt: DateTime
    updatedAt: DateTime
}

