scalar Date
scalar DateTime

type Query {
    getProfileByUserId(userId: ID!): UserProfile
}

type Mutation {
    updateMyProfile(userId: ID!, input: ProfileInput!): UserProfile
}

type UserProfile {
    id: ID
    userId: ID
    headline: String
    about: String
    bannerUrl: String
    avatarUrl: String
    location: String
    industry: String
    openToWork: Boolean
    lookingForJob: Boolean
    inCareerTransition: Boolean
    careerTransitionTarget: String
    acceptsEntryLevel: Boolean
    normalizedResume: String
    resumeScore: Int
    createdAt: DateTime
    updatedAt: DateTime
}

input ProfileInput {
    headline: String
    about: String
    bannerUrl: String
    avatarUrl: String
    location: String
    industry: String
    openToWork: Boolean
    lookingForJob: Boolean
    inCareerTransition: Boolean
    careerTransitionTarget: String
    acceptsEntryLevel: Boolean
    normalizedResume: String
}
